# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_auto_20190224_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneralSupplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HeatingCoolingProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MajorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('consultancy', models.ManyToManyField(blank=True, null=True, to='services.Consultancy')),
                ('general_suppl', models.ManyToManyField(blank=True, null=True, to='services.GeneralSupplies')),
                ('heat_prods', models.ManyToManyField(blank=True, null=True, to='services.HeatingCoolingProd')),
                ('lab', models.ManyToManyField(blank=True, null=True, to='services.Laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='MechanicalParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OnshoreEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolLogistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RehabCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RehabElectr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RehabMech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SafetyLabChem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WaterBoreHole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='mech_parts',
            field=models.ManyToManyField(blank=True, null=True, to='services.MechanicalParts'),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='onshore',
            field=models.ManyToManyField(blank=True, null=True, to='services.OnshoreEnv'),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='protologi',
            field=models.ManyToManyField(blank=True, null=True, to='services.ProtocolLogistics'),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='rehabcivil',
            field=models.ManyToManyField(blank=True, null=True, to='services.RehabCivil'),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='rehabelectr',
            field=models.ManyToManyField(blank=True, null=True, to='services.RehabElectr'),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='rehabmech',
            field=models.ManyToManyField(blank=True, null=True, to='services.RehabMech'),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='safety_lab_prods',
            field=models.ManyToManyField(blank=True, null=True, to='services.SafetyLabChem'),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='waterborehole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.WaterBoreHole'),
        ),
    ]
