# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-07 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20190307_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Haulage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MediPharma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='automob',
            field=models.ManyToManyField(blank=True, null=True, to='services.Automob'),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='calib',
            field=models.ManyToManyField(blank=True, null=True, to='services.Calibration'),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='haul',
            field=models.ManyToManyField(blank=True, null=True, to='services.Haulage'),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='hosp',
            field=models.ManyToManyField(blank=True, null=True, to='services.Hospitality'),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='intetest',
            field=models.ManyToManyField(blank=True, null=True, to='services.IntegrityTest'),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='medphr',
            field=models.ManyToManyField(blank=True, null=True, to='services.MediPharma'),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='printi',
            field=models.ManyToManyField(blank=True, null=True, to='services.Printing'),
        ),
    ]
