# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-09 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20190309_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineEng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InstallationUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='majorcategory',
            name='install',
            field=models.ManyToManyField(blank=True, null=True, to='services.InstallationUpgrade'),
        ),
        migrations.AddField(
            model_name='majorcategory',
            name='disc',
            field=models.ManyToManyField(blank=True, null=True, to='services.DisciplineEng'),
        ),
    ]
