# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-09 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20190309_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorcategory',
            name='installs',
            field=models.ManyToManyField(blank=True, null=True, to='services.InstallationUpgrade'),
        ),
        migrations.AlterField(
            model_name='majorcategory',
            name='install',
            field=models.ManyToManyField(blank=True, null=True, to='services.InstllMaintModel'),
        ),
    ]
