# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-20 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_file', models.FileField(upload_to='media/contrator/files')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateIncorporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certi_file', models.FileField(upload_to='media/contrator/files')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0)),
                ('no_of_staff', models.CharField(choices=[('0 - 10', '0 - 10'), ('10 - 20', '10 - 20')], max_length=75)),
                ('associated_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=75)),
                ('associated_company', models.CharField(max_length=75)),
                ('documents', models.FileField(upload_to='media/contrator/files')),
                ('machinary_plants_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=75)),
                ('subsidiary_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfileFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_profile_file', models.FileField(upload_to='media/contrator/files')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_certifct', models.FileField(upload_to='media/contrator/files')),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPersonDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=75)),
                ('designation', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='ContractorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=45)),
                ('logo', models.FileField(upload_to='images')),
                ('reg_no', models.CharField(max_length=45)),
                ('DPR_Permit_no', models.CharField(max_length=45)),
                ('TIN_no', models.CharField(max_length=45)),
                ('NIPEX_reg_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=45)),
                ('annual_turnover', models.IntegerField(default=0)),
                ('state_equity', models.CharField(max_length=50)),
                ('estimate_time', models.CharField(max_length=50)),
                ('submission_date', models.DateTimeField(auto_now=True)),
                ('signature', models.FileField(upload_to='media/contrator/files')),
            ],
        ),
        migrations.CreateModel(
            name='CountryCodeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_country', models.CharField(blank=True, max_length=200, null=True)),
                ('country_code', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DirectorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dir_nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel')),
            ],
        ),
        migrations.CreateModel(
            name='DPRCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpr_certi', models.FileField(upload_to='media/contrator/files')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel')),
            ],
        ),
        migrations.CreateModel(
            name='FormCO10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c010_file', models.FileField(upload_to='media/contrator/files')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel')),
            ],
        ),
        migrations.CreateModel(
            name='FormCO2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_file', models.FileField(upload_to='media/contrator/files')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel')),
            ],
        ),
        migrations.CreateModel(
            name='FormCO7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co7_file', models.FileField(upload_to='media/contrator/files')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgnztn_chart_file', models.FileField(upload_to='media/contrator/files')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel')),
            ],
        ),
        migrations.CreateModel(
            name='PastProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pjt_file', models.FileField(upload_to='media/contrator/files')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=255)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel')),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(blank=True, max_length=50, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel')),
            ],
        ),
        migrations.CreateModel(
            name='QMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_file', models.FileField(upload_to='media/contrator/files')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=45)),
                ('contact', models.CharField(max_length=45)),
                ('vendor', models.CharField(max_length=45)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('country_code', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.CountryCodeMaster')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatesMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=45, verbose_name='State Name')),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VATCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(upload_to='media/contrator/files')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel')),
            ],
        ),
        migrations.CreateModel(
            name='WCIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wcic_file', models.FileField(upload_to='media/contrator/files')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=255)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPerformanceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_exectn_date', models.DateField()),
                ('location', models.CharField(max_length=75)),
                ('total_value_contract', models.IntegerField()),
                ('client_contact_person', models.CharField(max_length=45)),
                ('job_compltn_certificate', models.FileField(upload_to='media/contrator/files')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel')),
            ],
        ),
        migrations.AddField(
            model_name='contractormodel',
            name='state_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.StatesMaster'),
        ),
        migrations.AddField(
            model_name='contractormodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactpersondetails',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel'),
        ),
        migrations.AddField(
            model_name='companytax',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel'),
        ),
        migrations.AddField(
            model_name='companyprofilefile',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel'),
        ),
        migrations.AddField(
            model_name='certificateincorporation',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel'),
        ),
        migrations.AddField(
            model_name='auditaccount',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel'),
        ),
    ]
