# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-17 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationmodel',
            old_name='place',
            new_name='company',
        ),
    ]
