# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-17 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190217_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='company',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='contact',
            field=models.CharField(max_length=45),
        ),
    ]
