# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-17 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20190217_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
