# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-17 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0005_registrationmodel_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=45)),
                ('logo', models.ImageField(upload_to='media/contrator/images')),
                ('reg_no', models.CharField(max_length=45)),
                ('DPR_Permit_no', models.CharField(max_length=45)),
                ('TIN_no', models.CharField(max_length=45)),
                ('NIPEX_reg_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatesMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=45, verbose_name='State Name')),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='contractormodel',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='contractormodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
