# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-17 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20190217_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='name',
            new_name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='contractormodel',
            name='contact',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='contract',
            field=models.ForeignKey(default=123123, on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel'),
        ),
    ]
