# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-17 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20190217_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractormodel',
            name='logo',
            field=models.FileField(upload_to='images'),
        ),
    ]
