# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_principalowner_registeredoffice_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractormodel',
            name='annual_turnover',
            field=models.IntegerField(default=0),
        ),
    ]
