# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_contractormodel_annual_turnover'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dir_nationality', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contractormodel',
            name='estimate_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractormodel',
            name='state_equity',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directordetails',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel'),
        ),
    ]
