# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_workperformancedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractormodel',
            name='state_origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.StatesMaster'),
            preserve_default=False,
        ),
    ]
