# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_contractormodel_service_catgry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractormodel',
            name='service_catgry',
        ),
    ]
