# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_wcic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0)),
                ('no_of_staff', models.IntegerField(default=0)),
                ('associated_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=75)),
                ('associated_company', models.CharField(max_length=75)),
                ('documents', models.FileField(upload_to='media/contrator/files')),
                ('machinary_plants_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=75)),
                ('subsidiary_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='contractormodel',
            name='signature',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/contrator/files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractormodel',
            name='submission_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel'),
        ),
    ]
