# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-23 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0026_auto_20190220_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='workperformancedetails',
            name='client_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
    ]
