# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-23 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0029_currentitf_healthcertificates_healthpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='media/contrator/files')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ContractorModel')),
            ],
        ),
    ]
