# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-23 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0030_otherdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractormodel',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='media/contrator/files'),
        ),
    ]
