# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0031_auto_20190223_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='workperformancedetails',
            name='job_compltn_certificate',
            field=models.FileField(upload_to='media/contrator/signatures'),
        ),
        migrations.AddField(
            model_name='contractormodel',
            name='service_catgry',
            field=models.ManyToManyField(blank=True, null=True, to='register.ServiceCategory'),
        ),
    ]
