# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 06:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0032_auto_20190224_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractormodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 2, 24, 6, 44, 27, 56749)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractormodel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
