# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0036_auto_20190305_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directordetails',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_dir', to='register.ContractorModel'),
        ),
        migrations.AlterField(
            model_name='principalowner',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_princi', to='register.ContractorModel'),
        ),
    ]
