# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0037_auto_20190305_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workperformancedetails',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_work', to='register.ContractorModel'),
        ),
    ]
