# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0038_auto_20190305_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateincorporation',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_inco', to='register.ContractorModel'),
        ),
        migrations.AlterField(
            model_name='companyprofilefile',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_prof', to='register.ContractorModel'),
        ),
        migrations.AlterField(
            model_name='contactpersondetails',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_contact', to='register.ContractorModel'),
        ),
    ]
